### ISSUE TITLE
stats - create a bootstrapped confidence intervals for t-test of sum_gamerounds ~ version

### ISSUE THREAD

**Issue by a-arad** [project-palooza/causal_inference#5]
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.bootstrap.html

**Comment by Sofia0204** [comment]
Hello, I'd like to do this one. Thanks c:

**Comment by Sofia0204** [comment]
Hi, I finished this issue, please review my pull request. Thanks.
