### ISSUE TITLE
stats - do power calculation for the t-test 

### ISSUE THREAD

**Issue by a-arad** [project-palooza/causal_inference#6]
calculate statistical power 

definition: https://en.wikipedia.org/wiki/Power_of_a_test

docs: https://stackoverflow.com/questions/54067722/calculate-power-for-t-test-in-python

**Comment by ang2887** [comment]
Hi  Arad,  I'd like to work on this issue. Can I take it? Lena

**Comment by ang2887** [comment]
Thanks!
  
  
  
  
  
  
  

  
  
>
